/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { KYC__factory } from "./KYC__factory";
export { SpCoinDataTypes__factory } from "./SpCoinDataTypes__factory";
